name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  pipeline:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 18.x ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: Create README file
        run: yarn run generate:readme
        env:
          UNSPLASH_API_KEY: ${{secrets.UNSPLASH_API_KEY}}
      - name: Push newly generated README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
